sudo: yes

services:
  - docker

before_install:
  - docker build -t client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run client-test npm run test -- --coverage

after_success:
  - docker build -t anuragkumarak1995/multi-client ./client
  - docker build -t anuragkumarak1995/multi-server ./server
  - docker build -t anuragkumarak1995/multi-worker ./worker
  - docker build -t anuragkumarak1995/multi-nginx  ./nginx
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and puch them to docker hub
  - docker push anuragkumarak1995/multi-client
  - docker push anuragkumarak1995/multi-server
  - docker push anuragkumarak1995/multi-worker
  - docker push anuragkumarak1995/multi-nginx

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "multi-docker-ankumar"
  env: "MultiDockerAnkumar-env-1"
  bucket_name: "elasticbeanstalk-us-west-2-823355659777"
  bucket_path: "multi-docker-ankumar"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
